# Using: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/appengine/standard_python3/django/app.yaml
runtime: python311

handlers:
# Serve a statically-generated version of the index page without spinning up the server.
# This is significantly faster (especially when the server instance goes to sleep),
# but requires the index.html file to be pre-generated.
- url: /(index\.html)?$
  static_files: staticfiles/index.html
  upload: staticfiles/index.html

# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: staticfiles/
  upload: staticfiles/(.*)

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
