# Generated by Django 4.2.4 on 2023-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datatype', models.CharField(max_length=30, null=True)),
                ('source', models.TextField(max_length=100, null=True)),
                ('destination', models.TextField(max_length=100, null=True)),
                ('explanation', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
