# Generated by Django 4.2.4 on 2024-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usecasefeedback_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.CharField(max_length=100)),
                ('user_meta_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
