name: Deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: 'python3 manage.py collectstatic'

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: portability-map
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Test gcloud CLI
        run: 'gcloud info'

          # Let's not try to actually deploy just yet
          #- name: Deploy to Cloud Run
          #run: gcloud app deploy --project=portability-map
