name: Lint JavaScript

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

